# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_aggregator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import hlo_pb2 as hlo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x61ta_aggregator.proto\x1a\thlo.proto\"\'\n\nHLOFEInput\x12\x19\n\x07service\x18\x01 \x01(\x0b\x32\x08.Service\"\x99\x01\n\x1bServiceComponentRequirement\x12\x37\n\x1cservice_component_definition\x18\x02 \x01(\x0b\x32\x11.ServiceComponent\x12\x41\n!infrastructure_element_candidates\x18\x01 \x03(\x0b\x32\x16.InfrastructureElement\"Z\n\x12HLOAllocatorOutput\x12\x44\n\x1eservice_component_requirements\x18\x01 \x03(\x0b\x32\x1c.ServiceComponentRequirementb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_aggregator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HLOFEINPUT._serialized_start=36
  _HLOFEINPUT._serialized_end=75
  _SERVICECOMPONENTREQUIREMENT._serialized_start=78
  _SERVICECOMPONENTREQUIREMENT._serialized_end=231
  _HLOALLOCATOROUTPUT._serialized_start=233
  _HLOALLOCATOROUTPUT._serialized_end=323
# @@protoc_insertion_point(module_scope)
